site_name: MinhaTirinha - Entrega 03
site_description: Documentação do projeto MinhaTirinha - Padrões de Projeto
site_url: https://github.com/UnBArqDsw2026-1-Turma01/2026.1-T01-G08_MinhaTirinha_Entrega_03

repo_url: https://github.com/UnBArqDsw2026-1-Turma01/2026.1-T01-G08_MinhaTirinha_Entrega_03
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UnBArqDsw2026-1-Turma01/2026.1-T01-G08_MinhaTirinha_Entrega_03

theme:
  name: material
  font:
    text: Nunito
    code: Fira Code
  palette:

    # Modo claro — tons pastéis
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: purple
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro

    # Modo escuro — pastel noturno
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro

  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.sections

extra_css:
  - stylesheets/pastel.css

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true

nav:
  - Home: index.md
  - Projetos: Projeto/Projeto.md
  - Padrões de Projeto:
    - Visão Geral: PadroesDeProjeto/3.PadroesDeProjeto.md
    - 3.1. GoFs Criacionais: PadroesDeProjeto/3.1.GoFsCriacionais.md
    - 3.2. GoFs Estruturais: PadroesDeProjeto/3.2.GoFsEstruturais.md
    - 3.3. GoFs Comportamentais: PadroesDeProjeto/3.3.GoFsComportamentais.md
    - 3.4. Participações: PadroesDeProjeto/3.4.ParticipacoesPadroes.md
    - 3.5. Iniciativas Extras: PadroesDeProjeto/3.5.IniciativasExtras.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences